export const GET_POKEMON_DATA = 'GET_POKEMON_DATA';
export const GET_POKEMON_INDIVIDUAL_DATA = 'GET_POKEMON_INDIVIDUAL_DATA';
export const GET_POKEMON_SPECIES_DATA = 'GET_POKEMON_SPECIES_DATA';
export const SET_GENERATION = 'SET_GENERATION';
export const SEARCH_POKEMON = 'SEARCH_POKEMON';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
export const SET_LOADING = 'SET_LOADING';
